[package]
name = "midi2opc"
version = "0.1.0"
authors = ["shybyte <ein@volloeko.de>"]

[dependencies]
portmidi = "^0.2.4"
chan-signal = "0.3.1"
rand="0.3"
chan = "0.1.19"
midi-message = { git = "https://github.com/shybyte/midi-message-rs" }